# Generated by Django 2.1.7 on 2019-03-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
